### ISSUE TITLE
Pull Request form for Amiibo database update.

### ISSUE THREAD

**Issue by N3evin** [N3evin/AmiiboAPI#106]
# Infomation
Please use the following form when doing a pull request for amiibo database. Do update the `amiibo.json` and  `game_info.json` file to prevent error and make sure proper testing had been done. If unsure on `game_info.json` please use the following format attached bellow and just set the games as empty array. Tick the `checklist` before submitting to ensure you have all the required information.

# Pull request form
### Checklist
 - [ ] The ids provided are not spoof.
 - [ ] The ids provided are all in lowercase.
 - [ ] The `game_info.json` had been updated with the corresponding ids.
 - [ ] Name of the amiibo matches [amiibo.life](https://amiibo.life/).
 - [ ] Images of amiibo had been provided with the highest quality.

### Link to amiibo.life for amiibo
- link_1
- link_2
- link_3
# Example for empty game_info
```json
"0x02ed0001015a0502":
{
	"games3DS": [],
	"gamesWiiU": [],
	"gamesSwitch": []
}
```

**Comment by AbandonedCart** [comment]
Can https://www.nintendo.com/store/hardware/amiibo/ be substituted for the links?

It's a bit confusing. amiibo.life is an unofficial database, not unlike this one. amiibo.life sources the spreadsheet you maintain, which references amiibo.life, which then needs to be referenced to submit info here. If amiibo.life already has the info being submitted here when it is submitted here, then there is no reason to submit it because you already have it.

**Comment by cheatfreak47** [comment]
> Can https://www.nintendo.com/store/hardware/amiibo/ be substituted for the links?
> 
> It's a bit confusing. amiibo.life is an unofficial database, not unlike this one. amiibo.life sources the spreadsheet you maintain, which references amiibo.life, which then needs to be referenced to submit info here. If amiibo.life already has the info being submitted here when it is submitted here, then there is no reason to submit it because you already have it.

The process typically goes like this:
1. Nintendo announces amiibo
1. amiibo.life makes a page for the new amiibo and populates metadata about it, including nice transparent png images
1. the amiibo releases.
1. I add the NFC data from privately sourced verified dumps to the spreadsheet database. (At this point I am the sole maintainer of the spreadsheet, pretty much)
1. amiibo.life and amiiboapi get the info from my spreadsheet and are updated with that, and then NFC data can be used to get images and metadata through either service

sometimes someone is able to get the real, accurate NFC data before the amiibo comes out, and in those situations, pull requests are accepted usually.

We prefer amiibo.life because it has it's own api for requesting images, it has actual data about what games are supported, and the pages never go down. The Nintendo store takes down pages for amiibo they longer sell or have any stock of, making it a poor choice of reference.

**Comment by cheatfreak47** [comment]
Bear in mind we also accept PRs anytime for corrections, additional metadata, or improving image quality anytime
I just mean that this is the process for *new* amiibo entries, usually

**Comment by AbandonedCart** [comment]
That makes sense. I know it's heresy, but I only got into this whole thing in 2020 (when I took over TagMo) and there isn't much of a welcome package if you weren't here from the beginning. Most, if not all, of the info and resources are from 2017. It's unexpected to see anyone doing much more than the absolute minimum amount of maintenance, so naturally I figured this wasn't much different (not to say that isn't still a lot of work, though).

**Comment by cheatfreak47** [comment]
Since hardly anyone probably reads much here anyway, here's some history on this project.

Basically, I bought an N2 elite at some point (2016 or so) and quickly realized the official app to manage it absolutely _sucked_. Going online, I realized that the absolute state of **all** things amiibo was a mess, it was just spoofed bin files everywhere and this resulted in hit-or-miss game compatibility and a plethroa of other problems, like finding bins with save files on them or whatever. So in the search for something better I met N3Evin (who maintained a now-defunct amiiqo/n2 elite app called amiibitz on an equally now-defunct website.) 

For a while and I helped him get good data by sourcing dumps of verified real amiibo, but we quickly realized that wasn't really enough to fix the mess everything was publicly- so eventually, N3evin and I put our heads together to make amiiboapi as a public resource- and I got in contact with the amiibo.life guy to help them add NFC info as well.

The goal was simple: Get all the **correct** NFC data publicly available and hopefully prevent the spread of incorrect NFC data. 

I'm probably glossing over some details here, but for the most part, that's the story. Basically it's just been kinda stagnant since then- partly because I was able to source verified NFC data for literally everything up to a point, even rare stuff like those japanese magazine-exclusive Animal Crossing cards. 

So, really the database is effectively complete until a new amiibo is released- and then we add it, and it's complete again for like 8 months, since Nintendo has really died down on releasing amiibo left and right, quite unlike the state of things back in 2016, with the amiibo card madness happening constantly.

Anyway, we actually **do** appreciate when PRs are made for newly released stuff, especially if it's not been added on the public repo yet, since often neither me nor n3evin have bothered to do it in a timely fashion. Historically we haven't been to stringent on enforcing the template, it's really just here to prevent people from submitting really bad pulls (hopefully).

**Comment by AbandonedCart** [comment]
Thanks for the info. Ironically, I got involved because I randomly decided to buy a Switch after they released the second generation and realized that amiibo were running for $50 each, not even remotely portable, and could burn out with use, but the only Android project didn't work with modern phones and had a pretty UI sitting in the PR queue. So here we are...

Now that I have a better understanding of how you're doing things, I should be able to step on a few less toes. Thanks again.
