### ISSUE TITLE
Splatoon 3 amiibo incorrect

### ISSUE THREAD

**Issue by PogChampMax** [N3evin/AmiiboAPI#108]
hey, i was trying to use the new Splatoon 3 Amiibos and they seemed perfectly fine but the Yellow Inkling one seems to be recognized as the Splatoon 1 Inkling
i even tried to create a new virtual amiibo for the yellow one but it still scans the Splatoon 1 version

**Comment by N3evin** [comment]
Hi,

When you said scans, is it in-game? I do not own the game for testing. However, the key in the db does not seems to conflict. Would love to see if there's anyone with similar issues.

**Comment by Cherrylord** [comment]
Heyo, I too have the same issue with the yellow inkling amiibo, when it gets scanned in-game it shows up as the Orange Splatoon 1 Inkling Girl and probably gives the same rewards as that amiibo instead of the Splatoon 3 Yellow Inkling's rewards

**Comment by N3evin** [comment]
Hi! We only deals with the key value in the amiibo. Maybe someone will post another bin from a legit copy of the amiibo and compare the key value. 

As for the game, I'm not too sure how the it's was reading it.

Maybe @cheatfreak47 have the key. Will have to check with him.

**Comment by N3evin** [comment]
We don't provides bin support, but do make sure it's coming from a legit source. It could be a fake/spoof bins, which I am unsure of if it's going around. Cheers.

**Comment by cheatfreak47** [comment]
I can confirm the data we have in our API is the **correct** data as dumped from the real Splatoon 3 amiibo.
If you are getting the incorrect Inkling in your game, chances are, the bin file you have is not using the full correct ID- meaning it's a badly spoofed bin.

The reason your bad `Inkling (Yellow)` bin is showing up as Splatoon 1 Inkling Girl, is that `Inkling Girl` and `Inkling (Yellow)` are both of the "Inkling Girl" character ID, but if the full ID isn't a match for `Inkling (Yellow)`. Sometimes games will just fall back to assuming it's just some unknown variant of the character ID that it matches.

**Comment by cheatfreak47** [comment]
Update: Just verified it, there's definitely spoofed bins floating around, which are likely to blame.

Legit Inkling Girl 
08000100-003E0402
Legit Inkling Yellow
08000100-04150402
Spoofed Inkling Yellow
08000100-**FFFF**0402

As you can see the bad spoof replaces the *only* part of the amiibo ID that is able to differentiate the original Inkling Girl from the new Inkling Yellow amiibo. This just leaves the game to have to **guess** what the amiibo is based on the anatomy of the ID, and this is inconsistent from bad spoof to bad spoof, since not all bad spoofs will use "FFFF" as the guesswork.

An interesting consequence of this is that if you currently have that bad FFFF spoof which the game currently sees as a Yellow Inkling, if Nintendo ever releases a new Inkling Girl variant that is higher than 0415, chances are your yellow spoof might be identified as a different, newer amiibo.
