### ISSUE TITLE
i have a idea

### ISSUE THREAD

**Issue by zyb1020** [N3evin/AmiiboAPI#11]
1.could you add the japanese name as release？

2.could i query amiibo by country? (like  'au/eu/jp/na')?

3.could you add gameSeries images?

4.could you add the official package image link?
like "https://www.nintendo.co.jp/hardware/amiibo/lineup/aaau/img/package.jpg",
and official images like
"https://www.nintendo.co.jp/hardware/amiibo/lineup/img/thumb/aaau.png",

キャプテン・ファルコン	aaau.png
ピット	aaas.png
リトル・マック	aaar.png
ゼルダ	aaaq.png
ディディーコング	aaap.png
ルイージ	aaan.png
マルス	aaam.png
カービィ	aaal.png
ピカチュウ	aaak.png
むらびと	aaaj.png
....

**Comment by N3evin** [comment]
1. I could try to add Japanese name when I had the time. Good idea.

2. Why would you want to query amiibo by country? I don't see is a necessary query. But I would try to add it into the api if there's a reason for it.

3. I am avoiding adding game series images, since I just want to focus on amiibo itself, rather than the game series, when developing an application, you guys just change use the information to determine game series and display appropriate images.

4. The images are based on their ID to look up easily since the information is already available in the NFC chip of each amiibo. Therefore, it is easier to look up their images by their id, instead of aaau.png, which does not make any sense in looking up for it.

**Comment by N3evin** [comment]
Close, due to no reply from the requester.
