### ISSUE TITLE
Wrong GameSeries in 2 amiibos

### ISSUE THREAD

**Issue by Andre-Anu** [N3evin/AmiiboAPI#167]
Hello!

so it's more of a overlook than a bug, but this 2 amiibos are with, gameSeries as "Breath of the Wild", and should be "The Legend of Zelda"
just like the amiibos from Tears of the Kingdom are!

that is all!

oh and I loved the API, using it for my assignment!
![image](https://github.com/N3evin/AmiiboAPI/assets/141456738/9b837f38-16d6-4d48-958f-e77b9e303d03)

**Comment by cheatfreak47** [comment]
Technically this is how it's supposed to be, so if Tears of the Kingdom is listing both it's amiibo series and gameseries as "Legend of Zelda" that would be incorrect actually

**Comment by cheatfreak47** [comment]
Hmm, examining the database, it seems the intended difference between amiibo series and game series is generally not well established in the data, so for the sake of consistency I agree this is in error, but I actually believe we're not populating amiiboseries and gameseries as distinctly as we aught to, other collaborators should contribute to this discussion probably, but my understanding is this was the intent originally:

amiiboSeries is supposed to denote the greater franchise, and gameSeries is supposed to denote sub-series' within that game series, so for example

All Zelda amiibo fall into the Legend of Zelda amiiboSeries, and individual runs of amiibo for specific games would be Breath of the Wild, Tears of the Kingdom, Skyward Sword HD, etc

As I said though at the moment this doesn't seem well reflected in the data so a lot of work would be needed to correct this.

**Comment by cheatfreak47** [comment]
It seems at the moment we currently use these mostly with Smash amiibo where the amiiboSeries is listed as Super Smash Bros. and gameSeries is listed as the franchise the character belongs to, but for everything else we haven't been denoting the amiibo series runs in the gameSeries spot at all.

A proper solution would be to introduce an additional data point to denote subSeries, but eh, maybe it's not necessary data.

**Comment by AbandonedCart** [comment]
Amiibo series is typically what it says on the top left of the box. Game series is typically the series from which they originate

![guardian](https://m.media-amazon.com/images/I/719f45nc2zL._SL1200_.jpg)
![bokobin](https://m.media-amazon.com/images/I/810cAZRyMDL._SL1500_.jpg)

That would make game series Breath of the Wild for these and Tears of the Kingdom for the others, but the game series Legend of Zelda for both.

**Comment by Andre-Anu** [comment]
Exactly, another thing that really shows the amiibo series in the figurines is the base of the model, they have the symbol of the amiibo series, like the super smash amiibos have the base as the smash ball from the series which is the same as the game symbol itself.

**Comment by cheatfreak47** [comment]
> Amiibo series is typically what it says on the top left of the box. Game series is typically the series from which they originate
> That would make amiibo series Breath of the Wild for these and Tears of the Kingdom for the others, but the game series Legend of Zelda for both.

The problem is we derive this information at the moment from the digits of the NFC ID, so we can't get any more specific than "Legend of Zelda" for say, "The Legend of Zelda: Breath of the Wild" is too specific because it will catch amiibo that are not part of the Breath of the Wild line.

All Zelda series amiibo use 010XXXXX-XXXX09XX IDs except for Guardian and Bokoblin which use 014XXXXX-XXXX09XX, which is why there is a distinction in the existing data, which as the OP suggests, seems in error compared to the rest of the data. It *technically* isn't an error, but rather a logical inconsistency.

The problem is that none of the other amiibo in the Zelda series of amiibo use 014, not even other Breath of the Wild ones. The rest all stick to 010. So as I said above, the data of the NFC IDs is a poor reference material for determining specific sub-series of amiibo.

A proper solution for this would be a subSeries tag where we populate this data and associate it to all IDs manually but we never ended up deciding to do that, iirc. It's something N3evin and I would probably be open to if someone wanted to submit a pull request or something though, as long as it's implemented well, but for now just fixing the discrepancy is fine.

**Comment by AbandonedCart** [comment]
I understood why the issue existed, which is because Nintendo went rogue on two statues, but you seemed to be unsure about how the categories correlated.

**Comment by cheatfreak47** [comment]
> I understood why the issue existed, which is because Nintendo went rogue on two statues, but you seemed to be unsure about how the categories correlated.
Oh yeah I see- I swipswapped the categories in my head last night when I commented, you're right- serves me right for commenting at 2 something in the morning haha

> I wonder if the bases for noah and mio are xenoblade. They seemed like they would have been primarily smash, but then the packaging said not. That one always stuck out as weird.
Nah this makes sense, Noah and Mio's amiibo are part of the Xenoblade line and have their own unique bases, and the amiibo only work for XC3. Noah and Mio aren't fighters in Smash, so the had to be part of their own line.

Anyway, I submitted a pull last night to fix the discrepancy, I'm sure @N3evin will merge it when he has a chance.

**Comment by AbandonedCart** [comment]
I wonder if it has anything to do with game compatibility.

**Comment by cheatfreak47** [comment]
> I wonder if it has anything to do with game compatibility.
Your guess is as good as anyone's I'd say. I believe that games seem just get passed the full ID of the amiibo when scanned and how they decide to interpret that data to decide what amiibo is what is up to the developer. 

I get the feeling that when Nintendo created the spec for amiibo IDs they probably had it planned out and were going to stick to it very rigidly but as time went on they just kind of floundered with making sure the spec was stuck to, and so everything has been ever-so-slightly more loosey-goosey since the Switch generation started.

There's a couple of other weird things too I get brought up to me, like how both Steve/Alex and Pyra/Mythra both share a single number when in the past, alt skins like Corrin, Bayonetta, and Cloud for example, had their alt-skins (called Player 2s for some reason) assigned a distinct number. I guess in those cases it's probably because the number is denoting the individual packs of amiibo, rather than individual statues since Steve/Alex and Pyra/Mythra are amiibo double packs, but it's been bought up because it is legitimately a strange choice.

**Comment by AbandonedCart** [comment]
I think it was more along the lines of someone suggested they do BotW as its own section and they either couldn't come to a unanimous decision or the memo got lost temporarily.

**Comment by Andre-Anu** [comment]
> I wonder if the bases for noah and mio are xenoblade. They seemed like they would have been primarily smash, but then the packaging said not. That one always stuck out as weird.

Yeah as you can see the base for the xenoblade 3 ones are grey not black like the smash ones, sadly I can't see from top, but even from side you can see the difference

![image](https://github.com/N3evin/AmiiboAPI/assets/141456738/2977e178-c90f-40f1-84a2-17a6635fa602)
![image](https://github.com/N3evin/AmiiboAPI/assets/141456738/a813eaf6-012e-4d18-8a05-2e03b0ed2b18)
