### ISSUE TITLE
Name or pic doesn't show after syncing with Amiibo API

### ISSUE THREAD

**Issue by Somenameee** [N3evin/AmiiboAPI#85]
![Screenshot_20211106-223428_TagMo](https://user-images.githubusercontent.com/93843541/140624535-3c827f61-faaf-4031-9081-bbfd8c39d55b.jpg)

I can't download or find the amiibo.json file either

**Comment by cheatfreak47** [comment]
First of all, your series 5 cards are fakes/spoofs, so that might have something to do with it.

**Comment by Somenameee** [comment]
Hmmm.. So there isn't any real bin files for series 5 yet?

**Comment by cheatfreak47** [comment]
No, there is, you just have fake ones. I feel like this problem is going to come up a lot due to the fake ones being widely distributed prerelease- but regardless of that AmiiboAPI only accepts the _real_ IDs for amiibo into it, not ones some redditor made up, even if they work.

Anyway, archive.org always has the latest set of bins if you go there and search for "Most Complete Amiibo Set" there. I posted the last update on Nov. 5th including legitimate Animal Crossing Series 5.

Please comment afterwards if you still have problems with bins that aren't fakes and I'll reopen the issue.

**Comment by cheatfreak47** [comment]
Oh also you can always get the amiibo.json from here:
https://github.com/N3evin/AmiiboAPI/tree/master/database

**Comment by Somenameee** [comment]
So i went by your comment and took the bin files from archive.org and they seem fine so don't need the .json anymore, thank you so much for help.
